### ISSUE TITLE
Building for Helix Editor

### ISSUE THREAD

**Issue by darrigu** [karlek/tree-sitter-nasm#2]
# Configuration

```toml
[[grammar]]
name = "nasm"
source = { git = "https://github.com/karlek/tree-sitter-nasm", rev = "ebf5aef830c792c61b119fbe4890de902a24896b" }
```

# Executed Command

```console
$ hx --grammar fetch
$ hx --grammar build
```

# Error Message

Error: Failed to build some grammar(s)

Caused by:
&nbsp;&nbsp;&nbsp;&nbsp;0: Failed to execute C compiler
&nbsp;&nbsp;&nbsp;&nbsp;1: No such file or directory (os error 2)
